### ISSUE TITLE
Hello Kaoto component sql-stored How to use? Any examples?

### ISSUE THREAD

**Issue by Alex-Bytes-A** [KaotoIO/kaoto-examples#16]
Want to configure sql stored procedure through Kaoto, found SQL-stored but will not use, would anyone use it? Can you give me an example? Thank you

**Comment by lhein** [comment]
Hello @longhai-he , how to use Stored Procedures with Camel is described at https://camel.apache.org/components/4.8.x/sql-stored-component.html. In Kaoto you can configure the "template" and the "templateOptions" then. "template" should point to a sql file containing your stored procedure call (alternatively you can also put it in the message body if I understand the description correctly but you then need to toggle on the "Use Message Body For Template" checkbox. The templateOptions are imo used to specify the parameters for the stored procedure call.

I put on a rough example code here but keep in mind it is not tested and you should also not put database credentials as text into your yaml file.

```
- route:
    id: route-2657
    from:
      id: from-2641
      uri: timer
      parameters:
        period: "1000"
        timerName: template
      steps:
        - log:
            id: log-3799
            message: ${body}
        - to:
            id: to-3293
            description: call stored procedure
            uri: sql-stored
            parameters:
              dataSource: "#postgres"
              template: classpath:sql/myStoredProcedure.sql
              template.param1: ${header.param1}
              template.param2: ${header.param2}
              template.param3: ${header.param3}
- beans:
    - name: postgres
      properties:
        databaseName: postgres
        password: postgres
        portNumber: "5432"
        serverName: localhost
        user: postgres
      type: org.postgresql.ds.PGSimpleDataSource

```
